### ISSUE TITLE
Bank Danamon Error

### ISSUE THREAD

**Issue by makanSukros** [fdciabdul/mutasi-scraper#14]
Bank Danamon no longer supports the https://www.danamonline.com url, I've tried it and got an error @fdciabdul

**Comment by fdciabdul** [comment]
> Bank Danamon no longer supports the https://www.danamonline.com url, I've tried it and got an error @fdciabdul

i don't have danamon ibank account anymore , if u have ibank account from danamon or other else.. 

you can email me abdulmuttaqin456@gmail.com

i will fix this
