### ISSUE TITLE
login looping with multiple bank accounts

### ISSUE THREAD

**Issue by makanSukros** [fdciabdul/mutasi-scraper#29]
I tested with several bank accounts, at first I managed to log in but after trying to login to 10/11 with a different account, after filling in the userid and paswd, I was redirected again to the login page with empty fields

**Comment by fdciabdul** [comment]
> I tested with several bank accounts, at first I managed to log in but after trying to login to 10/11 with a different account, after filling in the userid and paswd, I was redirected again to the login page with empty fields

https://github.com/fdciabdul/mutasi-scraper/blob/7ba1fdaf999bb4cd982c647811aaa6b5258589e7/lib/bank/BCA.class.js#L128

**Comment by fdciabdul** [comment]
fixed

**Comment by makanSukros** [comment]
> fixed

What solution did you do to solve the problem above?

**Comment by fdciabdul** [comment]
> > fixed
> 
> What solution did you do to solve the problem above?

update the libray to latest version , also please note that bca have some random time to block your action , maybe around 30 minutes
