### ISSUE TITLE
Scraper

### ISSUE THREAD

**Issue by ibengar** [fdciabdul/mutasi-scraper#32]
ini scrapper nya hnya untuk login akun sendiri ya? Saya mau membuat api nya menggunakan module dari anda agar oramg lain dapat login juga

**Comment by fdciabdul** [comment]
maksud nya gimana ya

**Comment by mattimmanuel01** [comment]
@ibengar tergantung cara buat API nya. API nya bisa dibikin agar parameters nya bisa di pass ke module scrapper nya. Atau bisa juga di hardcode di API nya tapi not recommended.
