### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by yagamicell** [fdciabdul/mutasi-scraper#38]
saya test selalu muncul eror seperti ini
setelah test npm run example dan isi data data yg sesuai.. hasil nya eror seperti itu

  var result = await scraper.getBCA(tglawal, blnawal, tglakhir, blnakhir);
                             ^

TypeError: scraper.getBCA is not a function
    at F:\github\mutasi-scraper-main\examples\example.js:28:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by fdciabdul** [comment]
silahkan fokus ke bagian README

untuk menjalankan cukup buat satu example script seperti ini
```javascript

const {ScrapBCA} = require('mutasi-scraper');

const user = 'USER';
const pass = 'PASS';

const scraper = new ScrapBCA(user, pass, {
  headless: false, // true if needed
  args: [
    '--log-level=3', 
    '--no-default-browser-check',
    '--disable-infobars',
    '--disable-web-security',
    '--disable-site-isolation-trials',
  ]
});

  const tglawal = "1 "; // tanggal 1
  const blnawal = "4"; // bulan 4
  const tglakhir = "30"; //ke tanggal 30
  const blnakhir = "4 "; // bulan 4

  var result = await scraper.getSettlement(tglawal, blnawal, tglakhir, blnakhir);
  console.log(result);
```

**Comment by yagamicell** [comment]
> silahkan fokus ke bagian README
> 
> untuk menjalankan cukup buat satu example script seperti ini
> 
> ```js
> const {ScrapBCA} = require('mutasi-scraper');
> 
> const user = 'USER';
> const pass = 'PASS';
> 
> const scraper = new ScrapBCA(user, pass, {
>   headless: false, // true if needed
>   args: [
>     '--log-level=3', 
>     '--no-default-browser-check',
>     '--disable-infobars',
>     '--disable-web-security',
>     '--disable-site-isolation-trials',
>   ]
> });
> 
>   const tglawal = "1 "; // tanggal 1
>   const blnawal = "4"; // bulan 4
>   const tglakhir = "30"; //ke tanggal 30
>   const blnakhir = "4 "; // bulan 4
> 
>   var result = await scraper.getSettlement(tglawal, blnawal, tglakhir, blnakhir);
>   console.log(result);
> ```

 var result = await scraper.getSettlement(tglawal, blnawal, tglakhir, blnakhir);
               ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.0.0

**Comment by fdciabdul** [comment]
@yagamicell sekarang tidak memungkinkan lagi untuk menjalankan pakai PHP
