### ISSUE TITLE
Error selector PSWD

### ISSUE THREAD

**Issue by andreaschrist27** [fdciabdul/mutasi-scraper#43]
hallo gan, pas coba kok error ya ?

**Comment by tanjiro142** [comment]
> hallo gan, pas coba kok error ya ?

Sama 😅

**Comment by fdciabdul** [comment]
Fixed

**Comment by andreaschrist27** [comment]
TimeoutError: Waiting for selector `#pswd` failed: Waiting failed: 30000ms exceeded

masih sama om, kira kira salah dmna ya ?

**Comment by tanjiro142** [comment]
> TimeoutError: Waiting for selector `#pswd` failed: Waiting failed: 30000ms exceeded
> 
> masih sama om, kira kira salah dmna ya ?

Ngestuck di dashboard setelah login kan ya? 
Abis itu log error #pswd

**Comment by andreaschrist27** [comment]
> > TimeoutError: Waiting for selector `#pswd` failed: Waiting failed: 30000ms exceeded
> > masih sama om, kira kira salah dmna ya ?
> 
> Ngestuck di dashboard setelah login kan ya? Abis itu log error #pswd

bener, login bisa lancar.
setelah itu stuck dan error

ini saya mau bantu jadi kontributor bljr nya puppeteer ya ? trus ada apa lagi ya selain itu ?

**Comment by fdciabdul** [comment]
ini seperti nya ada bug di update browser versi terbaru dari chrome / chromium 

saya mau coba pakai puppeteer-core

**Comment by fdciabdul** [comment]
soalnya di vps saya scraping masih lancar dengan chrome versi 113.0.5672

**Comment by fdciabdul** [comment]
![image](https://github.com/fdciabdul/mutasi-scraper/assets/31664438/a2a81137-404a-4cbe-b2a5-16ccc690e591)

**Comment by fdciabdul** [comment]
fixed
