### ISSUE TITLE
bug respon transaksi

### ISSUE THREAD

**Issue by CanD62** [fdciabdul/mutasi-scraper#44]
halo gan, baru nyoba scriptnya, dan ada bug di respon transaksinya, jadi seperti ini yang paling atas transaksi.
terimakasih

![image](https://github.com/fdciabdul/mutasi-scraper/assets/7421087/fd2c5a15-8924-4e25-84f2-181bdfb46553)

**Comment by tanjiro142** [comment]
> halo gan, baru nyoba scriptnya, dan ada bug di respon transaksinya, jadi seperti ini yang paling atas transaksi. terimakasih
> 
> ![image](https://user-images.githubusercontent.com/7421087/243246813-fd2c5a15-8924-4e25-84f2-181bdfb46553.png)

Di filter aja bro pake slice

**Comment by fdciabdul** [comment]
saya tau ini , dan sudah saya fix , beserta bank bni 

cuma belum saya push , nanti berbarengan dengan gojek / ovo

**Comment by CanD62** [comment]
baik, terimakasih.

**Comment by CanD62** [comment]
saya coba masih sama hasilnya
