### ISSUE TITLE
Error waktu new tab klik mutasi

### ISSUE THREAD

**Issue by CanD62** [fdciabdul/mutasi-scraper#48]
[PROXY] connected to remote server at accounts.google.com:443
[ LOG ] Starting ..
[PROXY] connected to remote server at ibank.klikbca.com:443
[PROXY] connected to remote server at www.googleapis.com:443
[PROXY] connected to remote server at chrome.google.com:443
[PROXY] connected to remote server at ibank.klikbca.com:443
[PROXY] connected to remote server at ibank.klikbca.com:443
[PROXY] connected to remote server at ibank.klikbca.com:443
[PROXY] connected to remote server at ibank.klikbca.com:443
[PROXY] connected to remote server at ibank.klikbca.com:443
[ LOG ] Login to BCA .. [*****]
[PROXY] connected to remote server at content-autofill.googleapis.com:443
[PROXY] connected to remote server at www.google.com:443
[ LOG ] Success login ..
[ LOG ] TypeError: Cannot read properties of undefined (reading 'startsWith')
[ LOG ] Logout..
{ status: false, error: null }

**Kode saya seperti ini**

> (async () => {
  const scraper = new ScrapBCA(user, pass, {
    headless: false, // true if needed
    args: [
      '--log-level=3', 
      '--no-default-browser-check',
      '--disable-infobars',
      '--disable-web-security',
      '--disable-site-isolation-trials',
    ],
   // executablePath: 'google-chrome', path google chrome  (uncomment line ini jika tidak diperlukan)  tapi direkomendasikan menggunakan google chrome 
  });

 

>  var result = await scraper.getStatement(tglawal, blnawal, tglakhir, blnakhir);

>   console.log(result);
> })();

**Comment by fdciabdul** [comment]
sertakan nomor rekening juga

```javascript 

new ScrapBCA(user, pass, norek,{
headless: false, // true if needed
args: [
'--log-level=3',
'--no-default-browser-check',
'--disable-infobars',
'--disable-web-security',
'--disable-site-isolation-trials',
],
// executablePath: 'google-chrome', path google chrome (uncomment line ini jika tidak diperlukan) tapi direkomendasikan menggunakan google chrome
});

```

**Comment by fdciabdul** [comment]
https://github.com/fdciabdul/mutasi-scraper/blob/e83d74d4aa18f7df9a1c845752b1b07530b503bd/lib/bank/BCA.class.js#L17

**Comment by roywikan** [comment]
> sertakan nomor rekening juga
> 
> ```js
> new ScrapBCA(user, pass, norek,{
> headless: false, // true if needed
> args: [
> '--log-level=3',
> '--no-default-browser-check',
> '--disable-infobars',
> '--disable-web-security',
> '--disable-site-isolation-trials',
> ],
> // executablePath: 'google-chrome', path google chrome (uncomment line ini jika tidak diperlukan) tapi direkomendasikan menggunakan google chrome
> });
> ```

sudah ditambahkan juga const norek dengan isi yang sudah benar, namun responnya sbb:

[ LOG ] Starting ..
[ LOG ] Login to BCA .. [USERNAMAKU]
[ LOG ] Success login ..
[ LOG ] TypeError: Cannot read properties of undefined (reading 'startsWith')
[ LOG ] Logout..

**Comment by fdciabdul** [comment]
@CanD62 @roywikan bisa di coba kaya gini  ?

```javascript
const { ScrapBCA } = require("mutasi-scraper");

(async () => {
    const bca = new ScrapBCA("username", "pass");
    const result = await bca.getStatement("01","7","10","7");
    console.log(result);
})();

```

disaya ngga ada masalah soal nya

**Comment by azivans21** [comment]
> 

Thanks, punya ku sudah bisa

Code di example.js
`// promisifying readline
const readline = require('readline');
const {ScrapBCA} = require("../");
const { promisify } = require('util');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
rl.question[promisify.custom] = (question) => {
  return new Promise(resolve => {
    rl.question(question, resolve);
  });
};
const questionAsync = promisify(rl.question).bind(rl);

(async () => {
  const bca = new ScrapBCA("username", "pass");
  const result = await bca.getStatement("01","7","10","7");
  console.log(result);
})();
`

**Comment by azivans21** [comment]
> @CanD62 @roywikan bisa di coba kaya gini ?
> 
> ```js
> const { ScrapBCA } = require("mutasi-scraper");
> 
> (async () => {
>     const bca = new ScrapBCA("username", "pass");
>     const result = await bca.getStatement("01","7","10","7");
>     console.log(result);
> })();
> ```
> 
> disaya ngga ada masalah soal nya

Thanks punya ku sudah bisa

**Comment by CanD62** [comment]
> @CanD62 @roywikan bisa di coba kaya gini ?
> 
> ```js
> const { ScrapBCA } = require("mutasi-scraper");
> 
> (async () => {
>     const bca = new ScrapBCA("username", "pass");
>     const result = await bca.getStatement("01","7","10","7");
>     console.log(result);
> })();
> ```
> 
> disaya ngga ada masalah soal nya

,

>  {
>     headless: false, // true if needed
>     args: [
>       '--log-level=3', 
>       '--no-default-browser-check',
>       '--disable-infobars',
>       '--disable-web-security',
>       '--disable-site-isolation-trials',
>     ],
>    // executablePath: 'google-chrome', path google chrome  (uncomment line ini jika tidak diperlukan)  tapi direkomendasikan menggunakan google chrome 
>   }

ini dihapus baru bisa

**Comment by roywikan** [comment]
> ```js
> "01","7","10","7");
> ```

MAAF baru sempat jawab.

iya itu bisa gan , nice... thank you!

ini kode yang saya modif dan jalan di node.js versi 18

`const { ScrapBCA } = require("mutasi-scraper");


(async () => {
    
    const user = 'YOURUSER01'; //YOUR USERNAME
    const pass = '123456'; //YOUR PIN
    
    
    const tglawal = "18";  // TANGGAL AWAL : 01-09 ATAU 11-31, tanpa spasi
    const blnawal = "7";   // BULAN AWAL : 1-9 ATAU 10-12, tanpa spasi
    const tglakhir = "20"; // TANGGAL AKHIR : 01-09 ATAU 11-31, tanpa spasi
    const blnakhir = "7";  // BULAN AKHIR : 1-9 ATAU 10-12, tanpa spasi
  
  
    const bca = new ScrapBCA(user, pass);
    const result = await bca.getStatement(tglawal,blnawal,tglakhir,blnakhir);
    console.log(result);
})();`

**Comment by Zikricikatech** [comment]
Kenapa pada saat new tab malah muncul form login lagi ya?

`
const { ScrapBCA } = require("mutasi-scraper");

(async () => {
    const bca = new ScrapBCA("username", "pass");
    const result = await bca.getStatement("01","7","10","7");
    console.log(result);
})();
`
