### ISSUE TITLE
UBUNTU SERVER

### ISSUE THREAD

**Issue by andreaschrist27** [fdciabdul/mutasi-scraper#49]
gan di local berfungsi dengan baik, knpa di ubuntu server gabisa ya ? 
Error nya : 

Error: Failed to launch the browser process!

**Comment by CanD62** [comment]
execute browsernya diarahkan coba

**Comment by fdciabdul** [comment]
install google chrome dulu di ubuntu servernya

**Comment by CanD62** [comment]
> install google chrome dulu di ubuntu servernya

punya saya juga seperti itu, pakai centos 7
kalau di lokal windows 11 lancar dan berjalan

**Comment by CanD62** [comment]
> install google chrome dulu di ubuntu servernya

seperti ini hasilnya


![image](https://github.com/fdciabdul/mutasi-scraper/assets/7421087/343df94b-13a0-4dc9-828c-281aea06ba38)

**Comment by roywikan** [comment]
> gan di local berfungsi dengan baik, knpa di ubuntu server gabisa ya ? Error nya :
> 
> Error: Failed to launch the browser process!

coba install chromenya gan.


# Add the Google Chrome repository
```bash
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
```
# Update the package index

```bash
sudo apt update
```

# Install Google Chrome
```bash
sudo apt install google-chrome-stable
```

**Comment by andreaschrist27** [comment]
> ```shell
> sudo apt install google-chrome-stable
> ```

karna diubuntu server ga ada GUI saya coba pake headless true bisa running, tpi pas mau scrape BCA nya yg malah gabisa. scrape BCAnya bisa nya pake headless false. apa saya yg masih ada salah setting ya ?

**Comment by CanD62** [comment]
> > ```shell
> > sudo apt install google-chrome-stable
> > ```
> 
> karna diubuntu server ga ada GUI saya coba pake headless true bisa running, tpi pas mau scrape BCA nya yg malah gabisa. scrape BCAnya bisa nya pake headless false. apa saya yg masih ada salah setting ya ?

Punya saya yang seperti di SS itu apanya bro?

**Comment by fdciabdul** [comment]
> > ```shell
> > sudo apt install google-chrome-stable
> > ```
> 
> karna diubuntu server ga ada GUI saya coba pake headless true bisa running, tpi pas mau scrape BCA nya yg malah gabisa. scrape BCAnya bisa nya pake headless false. apa saya yg masih ada salah setting ya ?

headlessnya pake "new" bukan tru/false 

secara default headless udah di set ke "new"

**Comment by roywikan** [comment]
> > > ```shell
> > > sudo apt install google-chrome-stable
> > > ```
> > 
> > 
> > karna diubuntu server ga ada GUI saya coba pake headless true bisa running, tpi pas mau scrape BCA nya yg malah gabisa. scrape BCAnya bisa nya pake headless false. apa saya yg masih ada salah setting ya ?
> 
> Punya saya yang seperti di SS itu apanya bro?

coba saya copas tutorial dari https://frugalisminds.com/how-to-setup-puppeteer-in-centos-7/ 


How to Setup Puppeteer in CentOS 7
Setup Puppeteer In CentOS 7 is easy but gets tricky in Linux distributions. Few weeks back we have Completed a project using puppeteer . Now the Question was Where Should we deploy ?

Our code is written in Windows and we wanted to move code to Production . Now we have CentOS 7 in prod . We were struggling to run Puppeteer on Prod machine .


Have a look at Environment details we have used to deploy a puppeteer .

Environment Details:–

[Puppeteer ](https://developers.google.com/web/tools/puppeteer)version: Latest
Platform / OS version: [CentOS 7](https://www.centos.org/download/)
Node JS version: [10 ](https://nodejs.org/dist/latest-v10.x/)or [12](https://nodejs.org/dist/v12.16.1/node-v12.16.1-x64.msi)
Have a look at Steps we Have Followed to Deploy A puppeteer backed application in CentOS 7

Step 1:- Install Node JS In CentOS 7

curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

yum install nodejs
Step 2 :- Install Puppeteer In CentOS 7
npm i puppeteer
Step 3 :- Install Chromium In CentOS 7

yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc
Step 4 :- Install Puppeteer In CentOs7
npm install --save puppeteer
Now Let’s Write a Sample Code to run Puppeteer in headless mode and name that file as test.js

'use strict';
const puppeteer = require('puppeteer');
const fs = require('fs');
(async () => {
  console.info("Starting browser");
  let browser;
  try {
    browser = await puppeteer.launch({});
  } catch (e) {
    console.info("Unable to launch browser mode in sandbox mode. Lauching Chrome without sandbox.");
    browser = await puppeteer.launch({args:['--no-sandbox']});
  }
  console.info("Browser successfully started");
  console.info("Closing browser");
  await browser.close();
  console.info("Done");
})();
Step 5 :- Run the Code , you will see the following output

image
running puppeteer centos7 without sandbox mode
Real problem starts here , We are not able to launch browser without --no-sandbox flag.

I Challenge most of you will face this problem while you setup puppeteer in Centos 7. SO Follow down this simple hack to solve this . I struggled a lot , I think you may or may not . But if you have reached this section of article then i firmly believe you have faced this as well.

For running Puppeteer in sandbox mode we need to do few changes as of now .

If you navigate to node_modules/puppeteer/.local-chromium/linux-549031, you notice that for puppeteer there is a file named chrome_sandbox (with an underscore).

Renaming this file to chrome-sandbox and perform following steps below


sudo mv chrome_sandbox chrome-sandbox
sudo chown root chrome-sandbox
sudo chmod 4755 chrome-sandbox
So what are we doing here ,

We are renaming the chrome_sandbox folder to chrome-sandbox as standard chromium searches for file with chrome-sandbox. Now run the test file again.


$ node test.js

Starting browser
Browser successfully started
Closing browser
Done
Conclusion :-
While running puppeteer we were facing issues Unable to connect to chrome . While searching on internet about the problem i got this solution . Hence sharing this with you all . Let me know if this helps .

References :-
https://github.com/puppeteer/puppeteer/issues/560

https://github.com/puppeteer/puppeteer/issues/497

https://github.com/puppeteer/puppeteer/issues/2857
