### ISSUE TITLE
linux/ubuntu server

### ISSUE THREAD

**Issue by mxsyxs** [fdciabdul/mutasi-scraper#51]
after click menu mutasi error "Error: No element found for selector: #startDt"
createTargetPage return login page.

**Comment by fdciabdul** [comment]
function sebelumnya sudah saya kasih deprecated 

boleh dicoba seperti ini 

```javascript
const { ScrapBCA } = require("mutasi-scraper");

(async () => {
    const bca = new ScrapBCA("username", "pass");
    const result = await bca.getStatement("01","7","10","7");
    console.log(result);
})();

```

**Comment by mxsyxs** [comment]
ya ini sudah pake getStatement. 
selalu Error: No element found for selector: #startDt

terkadang berhasil. tapi hanya 1 banding 10. lebih sering error no element found

**Comment by mxsyxs** [comment]
sebelumnya udh pernah coba hasilnya TimeoutError: Waiting for selector `#startDt` failed: Waiting failed: 30000ms exceeded

**Comment by fdciabdul** [comment]
kalau kaya gitu berarti server bca lagi maintance

**Comment by fdciabdul** [comment]
bisa di coba pakai proxy server singapore atau US untuk masalah kaya gitu

**Comment by mxsyxs** [comment]
testing di server sg hasilnya seperti itu.
sudah di tes pakai proxy indo juga sama.

dan anehnya testing in windows tidak ada kendala seperti itu.

**Comment by fdciabdul** [comment]
jangan terlalu cepet ngambil mutasi , 5 menit sekali

**Comment by tanjiro142** [comment]
> after click menu mutasi error "Error: No element found for selector: #startDt" createTargetPage return login page.
![Screenshot 2023-09-20 214733](https://github.com/fdciabdul/mutasi-scraper/assets/122802758/b7ab9865-ed8e-47ee-a706-c636f321dc1b)

Kiri Vps 8 menit sekali kanan windows 5 menit sekali
.
Wah iya nih saya testing di laptop windows aman tanpa trouble #startDT, ketika dijalankan di vps ubuntu dia sering banget error #startDT heran saya juga wkwk


Apakah sudah nemu solusinya? @mxsyxs
