### ISSUE TITLE
Bagaimana bisa melakukan cek mutasi secara berulang?

### ISSUE THREAD

**Issue by g00m00nry0ng** [fdciabdul/mutasi-scraper#53]
Kalau saya lakukan cek mutasi 1x dengan **npm run example**, prosesnya berhasil sampai muncul [ LOG ] Logout.. dan data mutasinya. Tapi tidak kembali ke command prompt. Jadi saya tidak bisa langsung mengulang **npm run example** lagi pada CLI yg sama.

Nah, kalau saya coba buka CLI baru dan saya jalankan **npm run example** hasilnya error sbb seakan-akan proses sebelumnya tidak selesais sempurna.

```
> mutasi-scraper@2.2.18 example
> node ./examples/example

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1080
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1887:7)
    at startServer (C:\Users\antonio\node_modules\mutasi-scraper\lib\helper\localProxy.js:5:42)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1778:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 1080
}
```

ada tips supaya saya bisa langsung jalankan cek mutasi berulang kali?

**Comment by fdciabdul** [comment]
kalau itu silahkan sesuai kan dengan kebutuhan nya , example itu hanya example 

contoh complete dari implementasi project ini bisa dilihat disini : 
https://mutasiku.imtaqin.id/
