### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by slopeng** [fdciabdul/mutasi-scraper#57]
[ LOG ] Login to BCA .. [xxxxxxx]
[PROXY] connected to remote server at content-autofill.googleapis.com:443
[PROXY] connected to remote server at www.google.com:443
[ LOG ] Success login ..
[ LOG ] TypeError: Cannot read properties of undefined (reading 'startsWith')
[ LOG ] Logout..
{ status: false, error: null }

**Comment by fdciabdul** [comment]
duplikat #52

**Comment by slopeng** [comment]
mantap joss
