### ISSUE TITLE
Error Loopback detected

### ISSUE THREAD

**Issue by dedekS1410web** [fdciabdul/mutasi-scraper#58]
![image](https://github.com/fdciabdul/mutasi-scraper/assets/38413544/c56b4de2-6920-484a-a3b8-7d364a76c57f)
kalau muncul itu trs kenapa ya mas ?

**Comment by fdciabdul** [comment]
> ![image](https://user-images.githubusercontent.com/38413544/265276566-c56b4de2-6920-484a-a3b8-7d364a76c57f.png) kalau muncul itu trs kenapa ya mas ?

normal .. itu dari sistem bca nya 

setelah 5-10 menit akan kembali normal 

itu dikarnakan login terlalu cepat
